services:
  ngnx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/config/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/certs:/etc/nginx/certs
    depends_on:
      - app
    networks:
      - orca
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
          WWWGROUP: '${WWWGROUP}'
    ports:
      - '${APP_PORT:-8081}:80'
      - '${APP_PORT_SECURE:-8082}:443'
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: laraveluser
      DB_PASSWORD: password
    networks:
      - orca
    labels:
      - traefik.enable=true
  node:
    image: node:14
    container_name: laravel_node
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: tail -f /dev/null

  db:
    image: mysql:5.7
    ports:
      - '${DB_PORT:-3306}:3306'
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - orca

volumes:
  dbdata:

networks:
  orca:
    external: true
